### ISSUE TITLE
add v4.2.1

### ISSUE THREAD

**Issue by lstkz** [jthomas/nodejs-v4-buildpack#1]
Latest version of nodejs is v4.2.1. Any chance to update buildpack?

**Comment by jthomas** [comment]
Let me look into this.

**Comment by jthomas** [comment]
I've discovered something odd. Despite not updating the manifest, if I set my node version to 4.x.x and this currently installs and run my application with 4.2.1. 
Looking through the code, I'm not exactly sure how this is happening but it is... 
Can you try this as well?

**Comment by lstkz** [comment]
Right, we can use original buildpack.
IBM docs are out of date
http://www.ibm.com/developerworks/web/nodesdk/

thanks
